site_name: Hackathon API
nav:
    - Card Service: index.md
    - Transaction: transaction.md
    - Invoice API: invoiceAPI.md
    - Auth Token: authToken.md
    - Card Service (Called by FE): cardAPI.md
    - Test Card: card.md
theme: readthedocs